name: build-SoC

on:
  push:
    branches:
      - main

jobs:
  build-SoC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: configure fpga-toolchain
      uses: YosysHQ/setup-oss-cad-suite@v1
      
    - name: configure riscv-toolchain
      uses: gregdavill/setup-riscv-gnu-toolchain@v1.0
      
    - name: configure python
      working-directory: ./litex
      run: |
        python3 -m pip install setuptools wheel Pillow Sphinx sphinxcontrib-wavedrom 

    - name: Litex build
      working-directory: ./litex
      run: |
        python3 SoC-CircuitPython.py
        python3 -m sphinx -M html build/documentation/ build/documentation/_build

    - name: Upload bitstream
      uses: actions/upload-artifact@v2
      with:
        name: OrangeCrab SoC Bitstream
        path: ${{ github.workspace }}/litex/build/orangecrab/gateware/orangecrab.dfu

    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: OrangeCrab SoC Docs
        path: ${{ github.workspace }}/litex/build/documentation/_build/html


    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/litex/build/documentation/_build/html