name: build-verilog-examples

on:
  push:
    branches:
      - main

jobs:
  build-verilog-examples:
    strategy:
      matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: configure fpga-toolchain
      uses: YosysHQ/setup-oss-cad-suite@v1

    - name: verilog.blink
      working-directory: ./verilog/blink
      run: make all

    - name: verilog.blink_reset
      working-directory: ./verilog/blink_reset
      run: make all

    - name: verilog.pwm_rainbow
      working-directory: ./verilog/pwm_rainbow
      run: make all
        
